"use client";
import { useEffect, useState } from "react";
import "./globals.css";
import Link from "next/link";

// export const metadata = {
//   title: "Web tutorials",
//   description: "Generated by cbk",
// };

export default function RootLayout({ children }) {
  const [topics, setTopics] = useState([]);
  useEffect(() => {
    fetch("http://localhost:9999/topics")
      .then((resp) => {
        return resp.json();
      })
      .then((result) => {
        setTopics(result);
      });
  });
  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topics) => {
            return (
              <li key={topics.id}>
                <Link href={`/read/${topics.id}`}>{topics.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <ul>
          <li>
            <Link href="/create">Create</Link>
          </li>
          <li>
            <Link href="/update/1">Update</Link>
          </li>
          <li>
            <input type="button" value="delete"></input>
          </li>
        </ul>
      </body>
    </html>
  );
}
